#!/usr/bin/env python3
import rospy
import numpy as np

from mouse_description.msg import SensorData

# Aggregates sensor data

outData = SensorData()

def main():
	ns = rospy.get_namespace()
	pub = rospy.Publisher(ns + 'sensor_data', SensorData, queue_size=10)

	r = rospy.Rate(30)
	while not rospy.is_shutdown():
		pub.publish(outData)
		r.sleep()

if __name__ == '__main__':
	rospy.init_node('sensor')
	try:
		main()
	except rospy.ROSInterruptException:
		pass