#!/usr/bin/env python3
import rospy

import curses

from mouse_description.msg import MouseCommand
from mouse_control.msg import UserMail

def main(stdscr):
	if rospy.get_param('/ANTS_USERCONTROL') and rospy.get_param('/BEES_USERCONTROL'):
		rospy.logerr('You tryna play urself?')
		exit(-1)
	elif rospy.get_param('/ANTS_USERCONTROL'):
		NUM = rospy.get_param('/NUM_ANTS')
		pub = rospy.Publisher('/ants/user', UserMail, queue_size=10)
		side = 'ant'
	elif rospy.get_param('/BEES_USERCONTROL'):
		NUM = rospy.get_param('/NUM_BEES')
		pub = rospy.Publisher('/bees/user', UserMail, queue_size=10)
		side = 'bee'
	else:
		rospy.logerr('Infect a Queen first!')
		exit(-1)

	# Curses setup
	stdscr.clear()
	curses.curs_set(False)
	index = 0

	msg = UserMail()
	msg.type = [MouseCommand.STOP] * NUM
	mcStr = ['FORWARD', 'LEFT', 'RIGHT', 'STOP', 'TELEPORT']

	while not rospy.is_shutdown():
		# Render screen
		stdscr.clear()
		stdscr.addstr(0, 0, f'Controlling {NUM} {side}s!')
		for i in range(NUM):
			stdscr.addstr(i+1, 0, f'{side}{i}: {mcStr[msg.type[i]]}', 
				curses.A_UNDERLINE if index==i else curses.A_NORMAL)
		stdscr.addstr(NUM+1, 0, 'Press space to send...')

		# Keystroke logic
		key = stdscr.getch()
		if key == ord('w'):
			msg.type[index] = MouseCommand.FORWARD
		elif key == ord('a'):
			msg.type[index] = MouseCommand.LEFT
		elif key == ord('s'):
			msg.type[index] = MouseCommand.STOP
		elif key == ord('d'):
			msg.type[index] = MouseCommand.RIGHT
		elif key >= ord('0') and key <= ord('9'):
			index = min(key - ord('0'), NUM-1)
		elif key == ord(' '):
			pub.publish(msg)

	# Curses cleanup
	curses.nocbreak()
	stdscr.keypad(False)
	curses.echo()
	curses.endwin()

if __name__ == '__main__':
	rospy.init_node('manualcontrol')
	try:
		curses.wrapper(main)
	except rospy.ROSInterruptException:
		pass