#!/usr/bin/env python3
import rospy, rosnode
from std_srvs.srv import Empty

NODES_KEEP = ['/rosout']

if __name__ == '__main__':
	rospy.init_node('killer')
	NODES_KEEP.append(rospy.get_name())

	try:
		print('Killing certain nodes...')
		for n in rosnode.get_node_names():
			if n not in NODES_KEEP:
				print('Killing', n)
				rosnode.kill_nodes([n])
	except Exception as e:
		print('FAILED!!! Just restart everything :(')
		print('Error message:', e)





	