#!/usr/bin/env python3
import rospy

import numpy as np

from mouse_description.msg import MouseCommand
from mouse_description.msg import MouseData

# Math helpers
def dist(x1, y1, x2, y2):
	return np.sqrt((y1-y2)**2 + (x1-x2)**2)

def main():
	r = rospy.Rate(30)
	while not rospy.is_shutdown():
		r.sleep()

if __name__ == '__main__':
	rospy.init_node('mothership')
	try:
		main()
	except rospy.ROSInterruptException:
		pass