#!/usr/bin/env python3
import rospy
import rospkg

import sys
import subprocess
import numpy as np

# world file parser helpers
wallPos, antPos, beePos, antFlag, beeFlag = [], [], [], None, None

def parseWorld(filename):
	f = open(filename, 'r')
	lines = f.readlines()
	lines.reverse()

	global antFlag, beeFlag
	for y in range(len(lines)):
		for x in range(len(lines[y])):
			if lines[y][x] == '#':
				wallPos.append((x, y))
			elif lines[y][x] == 'A':
				antPos.append((x,y))
			elif lines[y][x] == 'B':
				beePos.append((x,y))
			elif lines[y][x] == 'F':
				if y < len(lines) // 2:
					antFlag = (x,y)
				else:
					beeFlag = (x,y)
	beePos.reverse()

	rospy.set_param('WORLD_HEIGHT', max([p[1] for p in wallPos]) + 1)
	rospy.set_param('WORLD_WIDTH', max([p[0] for p in wallPos]) + 1)

# launch file alternatives
def find(pkg):
	return rospkg.RosPack().get_path(pkg)

def start_node(pkg, typ, name, ns='/', args=None):
	if args:
		subprocess.Popen(['rosrun', pkg, typ, f'__name:={name}', f'__ns:={ns}', *args.split(' ')], 
			stdin=subprocess.PIPE)
	else:
		subprocess.Popen(['rosrun', pkg, typ, f'__name:={name}', f'__ns:={ns}'], 
			stdin=subprocess.PIPE)

if __name__ == '__main__':
	rospy.init_node('spawner')

	WORLDFILENAME = rospy.get_param('WORLD_FILE')
	rospy.loginfo(f'Parsing {WORLDFILENAME} ...')
	parseWorld(WORLDFILENAME)

	rospy.loginfo('Spawning ants...')
	rospy.set_param('NUM_ANTS', len(antPos))
	for i, pos in enumerate(antPos):
		# start_node('mouse_description', 'sensor', 'sensor', f'ants/ant{i}')
		start_node('mouse_description', 'brain', 'brain', f'ants/ant{i}', f'-x {pos[0]} -y {pos[1]} -a {1}')

	rospy.loginfo('Spawning bees...')
	rospy.set_param('NUM_BEES', len(beePos))
	for i, pos in enumerate(beePos):
		# start_node('mouse_description', 'sensor', 'sensor', f'bees/bee{i}')
		start_node('mouse_description', 'brain', 'brain', f'bees/bee{i}', f'-x {pos[0]} -y {pos[1]} -a {3}')

	rospy.loginfo('Spawning the Insect God...')
	start_node('mouse_control', 'god', 'god')

	rospy.loginfo('Spawning Ant Queen...')
	start_node('mouse_control', 'mothership', 'mothership', 'ants')

	rospy.loginfo('Spawning Queen Bee...')
	start_node('mouse_control', 'mothership', 'mothership', 'bees')