<?xml version="1.0" ?>
<robot name="box" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="len" value="0.099"/>
	<xacro:property name="mass" value="1"/>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${len} ${len} ${len}"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${len} ${len} ${len}"/>
			</geometry>
		</collision>

		<inertial>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia
        		ixx="${1/6*mass*len*len}" ixy="0.0" ixz="0.0"
        		iyy="${1/6*mass*len*len}" iyz="0.0"
        		izz="${1/6*mass*len*len}"/>
		</inertial>
	</link>

	<gazebo reference="base_link">
		<mu1>1000000.0</mu1>
		<mu2>1000000.0</mu2>
		<material>Gazebo/Black</material>
	</gazebo>
</robot>
